### ISSUE TITLE
False positive bitcanna.io

### ISSUE THREAD

**Issue by BitCannaGlobal** [smashah/smashblock#7]
BitCanna is now marked in your list. BitCanna is not a company involved in spam, but focusses on solving issues in the cannabis industries using blockchain technology. Please remove our domain from your list (https://raw.githubusercontent.com/smashah/smashblock/master/blocklist.txt). Thanks!

**Comment by smashah** [comment]
@BitCannaGlobal i've made a new false positive handling system and added your website to it. thanks

**Comment by BitCannaGlobal** [comment]
Good day

Thank you!
